import type { FoodEquivalent, DailyBudget, MealBudget, FoodGroup, Routine } from '@/types'

// ==================== GYM ====================

export const ROUTINE_SCHEDULE: Record<number, string> = {
  1: 'upper_a',
  2: 'lower_a',
  3: 'rest',
  4: 'upper_b',
  5: 'lower_b',
  6: 'rest',
  0: 'rest',
}

export const ROUTINES: Record<string, Routine> = {
  upper_a: {
    name: 'Upper A',
    subtitle: 'Pecho, Hombro, Tríceps',
    muscles: ['Pecho', 'Hombros', 'Tríceps'],
    estimatedMinutes: 45,
    exercises: [
      {
        id: 'press-banca',
        name: 'Press de Banca',
        equipment: 'Mancuernas',
        sets: 4, reps: '8–10',
        lastWeight: 25, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'Acuéstate en el banco, pies firmes en el piso.',
          'Sostén una mancuerna en cada mano a los lados del pecho, codos a ~75°.',
          'Baja despacio hasta que los codos queden por debajo del banco.',
          'Empuja hacia arriba hasta casi juntar las mancuernas arriba.',
          'Más difícil que la barra — cada brazo trabaja de forma independiente.',
        ],
        tip: 'Si 25 lbs se sienten muy ligeras en las primeras reps, sube a 30 la siguiente serie.',
        substitutions: ['Smith Machine', 'Barra libre', 'Máquina de pecho'],
      },
      {
        id: 'press-militar',
        name: 'Press Militar',
        equipment: 'Mancuernas',
        sets: 4, reps: '10–12',
        lastWeight: 25, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'Siéntate con respaldo vertical, mancuernas a altura de hombros, palmas al frente.',
          'Empuja ambas mancuernas hacia arriba hasta casi juntar los brazos.',
          'Baja despacio hasta que los codos queden en 90°.',
          'No arquees la espalda baja al subir.',
        ],
        tip: 'La serie 4 se pone difícil — es normal bajar a 8 reps. No bajes el peso.',
        substitutions: ['Barra', 'Press Arnold', 'Máquina de hombro'],
      },
      {
        id: 'aperturas',
        name: 'Aperturas',
        equipment: 'Mancuernas en banco',
        sets: 3, reps: '12–15',
        lastWeight: 20, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'Acuéstate en el banco, mancuernas arriba con brazos casi extendidos.',
          'Baja los brazos hacia los lados con arco amplio, codos ligeramente doblados.',
          'Baja hasta sentir un buen estiramiento en el pecho.',
          'Sube siguiendo el mismo arco, como si abrazaras un árbol grande.',
        ],
        tip: 'Movimiento lento y controlado. El peso es secundario — enfócate en sentir el pecho.',
        substitutions: ['Pec Deck (máquina)', 'Poleas cruzadas'],
      },
      {
        id: 'elevaciones-laterales',
        name: 'Elevaciones Laterales',
        equipment: 'Mancuernas',
        sets: 3, reps: '12–15',
        lastWeight: 10, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'De pie, mancuernas a los costados, codos ligeramente doblados.',
          'Sube ambos brazos hacia los lados hasta paralelo al piso.',
          'Las muñecas al mismo nivel o ligeramente por debajo del codo.',
          'Baja de forma lenta y controlada — 2 a 3 segundos de bajada.',
          'No uses impulso del cuerpo ni eleves los hombros.',
        ],
        tip: '10 lbs se siente ligero pero quema bastante. No subas el peso a costa de balancearte.',
        substitutions: ['Polea lateral', 'Máquina de hombro lateral'],
      },
      {
        id: 'triceps-polea',
        name: 'Extensión de Tríceps',
        equipment: 'Polea con cuerda',
        sets: 3, reps: '12–15',
        lastWeight: 30, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la polea',
        instructions: [
          'Párate frente a la polea alta con la cuerda en ambas manos.',
          'Pega los codos al cuerpo — no deben moverse en todo el ejercicio.',
          'Empuja hacia abajo hasta extender completamente los brazos.',
          'Al llegar abajo, separa las puntas de la cuerda hacia afuera.',
          'Aprieta el tríceps 1 segundo, luego sube despacio.',
        ],
        tip: 'Si los codos se van hacia adelante al bajar, el peso es demasiado. Baja el pin.',
        substitutions: ['Extensión sobre cabeza', 'Fondos en banco'],
      },
    ],
  },

  lower_a: {
    name: 'Lower A',
    subtitle: 'Cuádriceps, Glúteos',
    muscles: ['Cuádriceps', 'Glúteos', 'Pantorrillas'],
    estimatedMinutes: 50,
    exercises: [
      {
        id: 'sentadilla',
        name: 'Sentadilla',
        equipment: 'Barra libre',
        sets: 4, reps: '8–10',
        lastWeight: 40, weightUnit: 'lbs',
        weightNote: 'Peso total en la barra (incluyendo barra ~45 lbs)',
        instructions: [
          'Coloca la barra en la parte alta de la espalda (no en el cuello).',
          'Pies al ancho de hombros, puntas ligeramente hacia afuera.',
          'Baja como si fueras a sentarte en una silla, rodillas siguiendo la dirección de los pies.',
          'Baja hasta que los muslos queden paralelos al piso o un poco más abajo.',
          'Sube empujando con los talones, no las puntas.',
        ],
        tip: 'Las primeras 2 series son de calentamiento. Sube el peso progresivamente.',
        substitutions: ['Smith Machine', 'Prensa de pierna', 'Sentadilla goblet con mancuerna'],
      },
      {
        id: 'prensa',
        name: 'Prensa de Pierna',
        equipment: 'Máquina',
        sets: 3, reps: '10–12',
        lastWeight: 90, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la máquina',
        instructions: [
          'Ajusta el asiento para que las rodillas queden a 90° al inicio.',
          'Pies al ancho de caderas en la plataforma.',
          'Baja la plataforma despacio hasta 90° de flexión de rodilla.',
          'Empuja hasta casi extender completamente, sin bloquear las rodillas.',
        ],
        tip: 'No dejes que las rodillas colapsen hacia adentro al subir.',
        substitutions: ['Sentadilla con barra', 'Hack squat'],
      },
      {
        id: 'extension-cuad',
        name: 'Extensión de Cuádriceps',
        equipment: 'Máquina',
        sets: 3, reps: '12–15',
        lastWeight: 50, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la máquina',
        instructions: [
          'Ajusta el respaldo para que la articulación de la rodilla quede alineada con el pivote.',
          'Extiende las piernas hasta casi rectas, aprieta el cuádriceps arriba.',
          'Baja despacio — 2 a 3 segundos de bajada.',
        ],
        tip: 'Ejercicio de aislamiento. Peso moderado, enfócate en sentir el cuádriceps quemar.',
        substitutions: [],
      },
      {
        id: 'zancadas',
        name: 'Zancadas',
        equipment: 'Mancuernas',
        sets: 3, reps: '10 por pierna',
        lastWeight: 20, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'De pie, mancuernas a los costados.',
          'Da un paso largo hacia adelante, baja la rodilla trasera casi al piso.',
          'La rodilla delantera no debe pasar la punta del pie.',
          'Empuja con el talón delantero para volver a la posición inicial.',
          'Alterna piernas o completa todas las reps de un lado.',
        ],
        tip: 'Mantén el torso recto y el core apretado durante todo el movimiento.',
        substitutions: ['Zancadas en máquina Smith', 'Step-ups con mancuernas'],
      },
      {
        id: 'pantorrillas',
        name: 'Elevación de Pantorrillas',
        equipment: 'Máquina o mancuernas',
        sets: 3, reps: '15–20',
        lastWeight: 30, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna o en máquina',
        instructions: [
          'De pie, punta de los pies en un escalón o superficie elevada.',
          'Talones abajo para obtener el estiramiento completo al inicio.',
          'Sube en punta de pies lo más alto posible.',
          'Mantén arriba 1 segundo, baja despacio.',
        ],
        tip: 'Las pantorrillas responden mejor a reps altas. No bajes el peso, sube las reps.',
        substitutions: ['Pantorrillas sentado en máquina'],
      },
    ],
  },

  upper_b: {
    name: 'Upper B',
    subtitle: 'Espalda, Bíceps',
    muscles: ['Espalda', 'Bíceps'],
    estimatedMinutes: 45,
    exercises: [
      {
        id: 'jalon',
        name: 'Jalón al Pecho',
        equipment: 'Polea',
        sets: 4, reps: '8–10',
        lastWeight: 60, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la polea',
        instructions: [
          'Siéntate en la máquina, agarra la barra un poco más ancho que los hombros.',
          'Inclínate ligeramente hacia atrás, pecho hacia arriba.',
          'Jala la barra hacia el pecho superior, apretando los codos hacia abajo y atrás.',
          'Controla la subida — no dejes que el peso suba solo.',
        ],
        tip: 'Piensa en jalar con los codos, no con las manos. Así activas más la espalda.',
        substitutions: ['Máquina de jalón', 'Dominadas asistidas'],
      },
      {
        id: 'remo-barra',
        name: 'Remo con Barra',
        equipment: 'Barra libre',
        sets: 3, reps: '8–10',
        lastWeight: 45, weightUnit: 'lbs',
        weightNote: 'Peso total en la barra',
        instructions: [
          'Párate con los pies al ancho de hombros, agarra la barra con agarre prono.',
          'Inclínate hacia adelante ~45°, espalda recta, rodillas ligeramente dobladas.',
          'Jala la barra hacia el abdomen bajo, codos cerca del cuerpo.',
          'Aprieta la espalda en la contracción, baja despacio.',
        ],
        tip: 'La espalda recta es lo más importante. Si se redondea, baja el peso.',
        substitutions: ['Remo en máquina', 'Remo mancuerna dos manos'],
      },
      {
        id: 'remo-mancuerna',
        name: 'Remo Mancuerna',
        equipment: 'Mancuerna (1 mano)',
        sets: 3, reps: '10–12',
        lastWeight: 30, weightUnit: 'lbs',
        weightNote: 'Peso de la mancuerna (una mano a la vez)',
        instructions: [
          'Apoya la rodilla y mano del mismo lado en el banco.',
          'La espalda debe quedar paralela al piso.',
          'Jala la mancuerna hacia la cadera, codo pegado al cuerpo.',
          'Baja despacio hasta extensión completa del brazo.',
          'Completa todas las reps de un lado antes de cambiar.',
        ],
        tip: 'Rango de movimiento completo — baja hasta que el brazo quede completamente extendido.',
        substitutions: [],
      },
      {
        id: 'curl-biceps',
        name: 'Curl de Bíceps',
        equipment: 'Barra',
        sets: 3, reps: '10–12',
        lastWeight: 30, weightUnit: 'lbs',
        weightNote: 'Peso total en la barra',
        instructions: [
          'De pie, agarra la barra con agarre supino al ancho de hombros.',
          'Codos pegados al cuerpo — no se mueven durante el ejercicio.',
          'Sube la barra hasta contraer completamente el bíceps.',
          'Baja despacio y con control total.',
        ],
        tip: 'Si los codos se van hacia adelante al subir, el peso es demasiado.',
        substitutions: ['Curl con mancuernas alternas'],
      },
      {
        id: 'curl-martillo',
        name: 'Curl Martillo',
        equipment: 'Mancuernas',
        sets: 3, reps: '12–15',
        lastWeight: 20, weightUnit: 'lbs',
        weightNote: 'Peso por mancuerna (cada mano)',
        instructions: [
          'De pie, mancuernas a los costados con agarre neutro (pulgares arriba).',
          'Sube alternando brazos o los dos a la vez.',
          'Codos fijos, sube hasta contraer el bíceps y el braquial.',
          'Baja despacio.',
        ],
        tip: 'El curl martillo trabaja el braquial, que da grosor al brazo. No lo saltes.',
        substitutions: [],
      },
    ],
  },

  lower_b: {
    name: 'Lower B',
    subtitle: 'Isquiotibiales, Glúteos, Core',
    muscles: ['Isquiotibiales', 'Glúteos', 'Core'],
    estimatedMinutes: 50,
    exercises: [
      {
        id: 'peso-muerto',
        name: 'Peso Muerto',
        equipment: 'Barra libre',
        sets: 4, reps: '6–8',
        lastWeight: 60, weightUnit: 'lbs',
        weightNote: 'Peso total en la barra',
        instructions: [
          'Pies al ancho de caderas, barra sobre el medio del pie.',
          'Agáchate y agarra la barra justo afuera de las rodillas.',
          'Espalda recta, pecho hacia arriba, mirada al frente.',
          'Empuja el piso con los pies para subir — no jales con la espalda.',
          'Las caderas y los hombros suben al mismo tiempo.',
          'Al bajar, primero van las caderas atrás, luego doblas las rodillas.',
        ],
        tip: 'El ejercicio más técnico. Si sientes la espalda baja, para y baja el peso.',
        substitutions: ['Peso muerto rumano con mancuernas', 'Hip hinge en máquina'],
      },
      {
        id: 'curl-femoral',
        name: 'Curl Femoral',
        equipment: 'Máquina',
        sets: 3, reps: '12–15',
        lastWeight: 40, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la máquina',
        instructions: [
          'Acuéstate boca abajo en la máquina, rodillas alineadas con el pivote.',
          'Dobla las rodillas jalando los talones hacia los glúteos.',
          'Aprieta los isquiotibiales en la contracción.',
          'Baja despacio — no dejes caer el peso.',
        ],
        tip: 'No levantes las caderas al subir. Si lo haces, el peso es demasiado.',
        substitutions: [],
      },
      {
        id: 'hip-thrust',
        name: 'Hip Thrust',
        equipment: 'Barra o mancuerna',
        sets: 3, reps: '10–12',
        lastWeight: 45, weightUnit: 'lbs',
        weightNote: 'Peso total (barra o mancuerna sobre las caderas)',
        instructions: [
          'Apoya la parte alta de la espalda en un banco.',
          'Coloca la barra o mancuerna sobre las caderas.',
          'Pies al ancho de caderas, rodillas a 90° cuando estés arriba.',
          'Empuja las caderas hacia arriba apretando los glúteos.',
          'Mantén 1 segundo arriba, baja despacio.',
        ],
        tip: 'El mejor ejercicio para glúteos. Aprieta fuerte arriba en cada rep.',
        substitutions: ['Puente de glúteos en el piso'],
      },
      {
        id: 'abduccion',
        name: 'Abducción de Cadera',
        equipment: 'Máquina',
        sets: 3, reps: '15',
        lastWeight: 50, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la máquina',
        instructions: [
          'Siéntate en la máquina con las piernas juntas al inicio.',
          'Abre las piernas hacia afuera en contra de la resistencia.',
          'Aprieta los glúteos en el punto de máxima apertura.',
          'Cierra despacio y con control.',
        ],
        tip: 'Reps altas, peso moderado. Enfócate en sentir el glúteo medio.',
        substitutions: [],
      },
      {
        id: 'plancha',
        name: 'Plancha Abdominal',
        equipment: 'Sin equipo',
        sets: 3, reps: '30–45 seg',
        lastWeight: 0, weightUnit: 'seg',
        weightNote: 'Sin peso — registra los segundos completados',
        instructions: [
          'Apoya los antebrazos y las puntas de los pies en el piso.',
          'El cuerpo debe formar una línea recta de cabeza a talones.',
          'Aprieta el abdomen, los glúteos y los cuádriceps.',
          'No dejes que las caderas suban ni bajen.',
          'Respira de forma constante.',
        ],
        tip: 'Si 45 seg se siente fácil, extiende a 60 seg o agrega elevación de pierna.',
        substitutions: ['Crunch en polea', 'Crunch en máquina'],
      },
      {
        id: 'crunch-polea',
        name: 'Crunch en Polea',
        equipment: 'Polea',
        sets: 3, reps: '15',
        lastWeight: 20, weightUnit: 'lbs',
        weightNote: 'Peso en el pin de la polea',
        instructions: [
          'Arrodíllate frente a la polea alta con la cuerda detrás de la cabeza.',
          'Dobla el torso hacia abajo contrayendo el abdomen.',
          'El movimiento viene del abdomen, no de las caderas.',
          'Sube despacio a la posición inicial.',
        ],
        tip: 'No jales con los brazos. El abdomen hace todo el trabajo.',
        substitutions: ['Crunch en el suelo', 'Crunch en máquina'],
      },
    ],
  },
}

export const FEELING_OPTIONS = [
  { value: 'muy_pesado', label: 'Muy pesado', emoji: '😫' },
  { value: 'dificil', label: 'Difícil', emoji: '😤' },
  { value: 'perfecto', label: 'Perfecto', emoji: '💪' },
  { value: 'ligero', label: 'Ligero', emoji: '😊' },
  { value: 'quiero_mas', label: 'Quiero más', emoji: '🔥' },
] as const

// ==================== ALIMENTACIÓN ====================

export const DAILY_BUDGET: DailyBudget = {
  verdura: 4,
  fruta: 2,
  carb: 4,
  leguminosa: 1,
  proteina: 8,
  grasa: 6,
}

export const MEAL_BUDGETS: Record<string, MealBudget> = {
  desayuno: { verdura: 0, fruta: 0, carb: 0, leguminosa: 0, proteina: 3, grasa: 0 },
  snack: { verdura: 0, fruta: 2, carb: 1, leguminosa: 0, proteina: 0, grasa: 2 },
  comida: { verdura: 2, fruta: 0, carb: 1, leguminosa: 1, proteina: 3, grasa: 2 },
  cena: { verdura: 2, fruta: 0, carb: 2, leguminosa: 0, proteina: 2, grasa: 2 },
}

export const FOOD_GROUP_LABELS: Record<FoodGroup, string> = {
  verdura: 'Verdura',
  fruta: 'Fruta',
  carb: 'Carbohidrato',
  proteina: 'Proteína',
  grasa: 'Grasa',
  leguminosa: 'Leguminosa',
}

export const FOOD_GROUP_COLORS: Record<FoodGroup, string> = {
  verdura: '#22c55e',
  fruta: '#f97316',
  carb: '#eab308',
  proteina: '#ef4444',
  grasa: '#8b5cf6',
  leguminosa: '#06b6d4',
}

export const FRUITS: FoodEquivalent[] = [
  { name: 'Agua de coco', portion: '1 bote' },
  { name: 'Arándanos deshidratados', portion: '¼ tza' },
  { name: 'Blueberries', portion: '½ taza' },
  { name: 'Cereza', portion: '8-10 pzas' },
  { name: 'Chabacano', portion: '2 pzas' },
  { name: 'Ciruela grande', portion: '1 pza' },
  { name: 'Dátil', portion: '2 pzas' },
  { name: 'Durazno', portion: '1 pza' },
  { name: 'Frambuesa', portion: '1 tza' },
  { name: 'Fresa', portion: '1 tza (6-8 pzas)' },
  { name: 'Guayaba', portion: '1 pza' },
  { name: 'Higo', portion: '3 pzas' },
  { name: 'Kiwi', portion: '2 pzas' },
  { name: 'Lichi', portion: '6 pzas' },
  { name: 'Mamey', portion: '¼ pza' },
  { name: 'Mandarina', portion: '2 pzas' },
  { name: 'Mango', portion: '½ pza' },
  { name: 'Manzana', portion: '1 pza' },
  { name: 'Melón', portion: '1 tza' },
  { name: 'Moras', portion: '1 tza' },
  { name: 'Naranja', portion: '2 pzas' },
  { name: 'Papaya', portion: '1 taza' },
  { name: 'Pera', portion: '1 pza' },
  { name: 'Pasitas', portion: '10 pzas' },
  { name: 'Piña', portion: '1 taza' },
  { name: 'Plátano', portion: '½ pza' },
  { name: 'Sandía', portion: '1 taza' },
  { name: 'Toronja', portion: '1 pza' },
  { name: 'Uvas', portion: '8-10 pzas' },
  { name: 'Mermelada natural', portion: '1 cda' },
]

export const VEGETABLES: FoodEquivalent[] = [
  { name: 'Alcachofa', portion: '1 pza' },
  { name: 'Apio', portion: '2 pzas' },
  { name: 'Betabel', portion: '½ pza' },
  { name: 'Berenjena', portion: '1 pza' },
  { name: 'Brócoli', portion: '1 tza' },
  { name: 'Calabaza', portion: '1 pza' },
  { name: 'Champiñón', portion: '1 tza' },
  { name: 'Chayote', portion: '1 tza' },
  { name: 'Col', portion: '1 tza' },
  { name: 'Ejote', portion: '1 tza' },
  { name: 'Elotitos cambray', portion: '8 pzas' },
  { name: 'Espárragos', portion: '6 pzas' },
  { name: 'Espinaca cruda', portion: '3 tzas' },
  { name: 'Espinaca cocida', portion: '1 tza' },
  { name: 'Jícama', portion: '1 tza' },
  { name: 'Jitomate deshidratado', portion: '5 pzas' },
  { name: 'Jitomate bola', portion: '1 pza' },
  { name: 'Lechuga', portion: '3 tzas' },
  { name: 'Nopal', portion: '1 tza' },
  { name: 'Pepino', portion: '1 pza' },
  { name: 'Setas', portion: '1 tza' },
  { name: 'Zanahoria', portion: '2 pzas' },
  { name: 'Palmitos', portion: '6-8 pzas (1 lata)' },
]

export const CARBS: FoodEquivalent[] = [
  { name: 'Arroz cocido (preferir integral)', portion: '½ tza' },
  { name: 'Avena cruda', portion: '⅓ tza' },
  { name: 'Avena cocida', portion: '½ tza' },
  { name: 'Bagel', portion: '½ pza' },
  { name: 'Bolillo sin migajón', portion: '½ pza' },
  { name: 'Pan hamburguesa', portion: '½ pza' },
  { name: 'Cereal integral de caja', portion: '1 tza' },
  { name: 'Chapata sin migajón', portion: '½ pza' },
  { name: 'Elote desgranado', portion: '½ tza' },
  { name: 'Elote entero', portion: '1 chico' },
  { name: 'Palomitas naturales', portion: '2 tzas' },
  { name: 'Pasta cocida', portion: '1 tza' },
  { name: 'Pan integral', portion: '1 pza' },
  { name: 'Pan árabe', portion: '½ pza' },
  { name: 'Pan de hot dog', portion: '½ pza' },
  { name: 'Papa cocida', portion: '1 pza chica' },
  { name: 'Papa cambray', portion: '4-5 pzas' },
  { name: 'Puré de papa', portion: '½ tza' },
  { name: 'Salmas', portion: '1 paquete' },
  { name: 'Tortilla maíz', portion: '1 pza' },
  { name: 'Tortilla nopal', portion: '2 pzas' },
  { name: 'Tostadas sanísimo', portion: '2 pzas' },
  { name: 'Rice cakes', portion: '2 pzas' },
]

export const LEGUMES: FoodEquivalent[] = [
  { name: 'Frijol cocido / lenteja', portion: '⅓ taza' },
  { name: 'Garbanzo cocido', portion: '1 tza' },
  { name: 'Hummus', portion: '⅓ tza' },
  { name: 'Edamames', portion: '⅓ tza' },
]

export const PROTEINS: FoodEquivalent[] = [
  { name: 'Anillos de calamar', portion: '4 pzas' },
  { name: 'Atún en agua', portion: '1 lata' },
  { name: 'Bistec', portion: '1 palma de la mano' },
  { name: 'Carne molida', portion: '1 bola (pelota béisbol)' },
  { name: 'Carne deshebrada', portion: '¾ tza' },
  { name: 'Pollo deshebrado', portion: '¾ tza' },
  { name: 'Camarón U8', portion: '3 pzas' },
  { name: 'Camarón normal', portion: '6 pzas' },
  { name: 'Huevo', portion: '1 pza' },
  { name: 'Claras de huevo', portion: '2 pzas' },
  { name: 'Jamón', portion: '5 rebanadas' },
  { name: 'Jocoque', portion: '1 cda' },
  { name: 'Filete', portion: 'Palma de la mano' },
  { name: 'Pescado', portion: 'Palma de la mano con dedos' },
  { name: 'Pavo', portion: 'Palma de la mano con dedos' },
  { name: 'Salmón', portion: 'Palma de la mano con dedos' },
  { name: 'Queso cottage', portion: '2-3 cdas soperas' },
  { name: 'Queso panela/oaxaca/mozarella/feta', portion: 'Palma con dedos' },
  { name: 'Yogurt griego', portion: '1 botesito', note: 'Cuenta como 1 proteína + 1 grasa' },
  { name: 'Leche light', portion: '1 taza' },
]

export const FATS: FoodEquivalent[] = [
  { name: 'Aguacate', portion: '⅓ pza' },
  { name: 'Nueces/pistache/almendra/avellana/cacahuate natural', portion: '10-12 pzas' },
  { name: 'Aceitunas', portion: '4 pzas' },
  { name: 'Crema de avellana', portion: '1 cda' },
  { name: 'Crema de almendra', portion: '1 cda' },
  { name: 'Crema de cacahuate', portion: '1 cda' },
  { name: 'Jocoque', portion: '1 cda sopera' },
  { name: 'Chocolate amargo Turín sin azúcar', portion: '2 chiquitos' },
  { name: 'Queso cabra', portion: '⅓ barra chica' },
]

export const FOOD_EQUIVALENTS: Record<FoodGroup, FoodEquivalent[]> = {
  fruta: FRUITS,
  verdura: VEGETABLES,
  carb: CARBS,
  leguminosa: LEGUMES,
  proteina: PROTEINS,
  grasa: FATS,
}

// ==================== HÁBITOS INICIALES ====================

export const DEFAULT_HABITS = [
  {
    name: 'Agua',
    type: 'quantity' as const,
    target_value: 2,
    unit: 'litros',
  },
  {
    name: 'Lectura',
    type: 'weekly_frequency' as const,
    target_value: 4,
    unit: 'días/semana',
  },
  {
    name: 'Creatina',
    type: 'daily_check' as const,
    target_value: null,
    unit: null,
  },
]

// ==================== USUARIO ====================

export const USER_PROFILE = {
  initialWeight: 86,
  height: 163,
  goalWeight: 79,
  initialBMI: 32.4,
}
